# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialogue(object):
    def setupUi(self, AboutDialogue):
        AboutDialogue.setObjectName("AboutDialogue")
        AboutDialogue.resize(693, 669)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/proz_icon_simple.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDialogue.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AboutDialogue)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(AboutDialogue)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(AboutDialogue)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/projz_icon.ico"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(AboutDialogue)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(AboutDialogue)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(AboutDialogue)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(AboutDialogue)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(AboutDialogue)
        self.pushButton.clicked.connect(AboutDialogue.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialogue)

    def retranslateUi(self, AboutDialogue):
        _translate = QtCore.QCoreApplication.translate
        AboutDialogue.setWindowTitle(_translate("AboutDialogue", "About"))
        self.label_2.setText(_translate("AboutDialogue", "<html><head/><body><h2>Projz - RenyPy Translation Toolkit</h2></body></html>"))
        self.label_3.setText(_translate("AboutDialogue", "Github: <a href=\"https://github.com/abse4411/projz_renpy_translation\">projz_renpy_translation</a>"))
        self.label_4.setText(_translate("AboutDialogue", "Licence: <a href=\"https://github.com/abse4411/projz_renpy_translation?tab=GPL-3.0-1-ov-file\">GPL-3.0</a>"))
        self.label_5.setText(_translate("AboutDialogue", "<html><head/><body><h2>🔗Acknowledgement</h2><p><ul dir=\"auto\">\n"
"<li>Previous code of Web translation: <a href=\"https://github.com/Maooookai/WebTranslator\">Maooookai(Mirage)</a>, <a href=\"https://github.com/drdrr/RenPy-WebTranslator\">DrDRR</a></li>\n"
"<li>AI translation: <a href=\"https://github.com/xhluca/dl-translate\">dl-translate</a>, <a href=\"https://github.com/xhluca/dl-translate?tab=MIT-1-ov-file\">MIT License</a></li>\n"
"<li><a href=\"https://github.com/UlionTse/translators\">UlionTse/translators</a>, <a href=\"https://github.com/UlionTse/translators?tab=GPL-3.0-1-ov-file\">GPL-3.0 License</a></li>\n"
"<li>Pre-translated RPY file: <a href=\"https://github.com/renpy/renpy/tree/master/launcher/game/tl\">RenPy</a>, <a href=\"https://www.renpy.org/doc/html/license.html\" rel=\"nofollow\">MIT License for these rpy files</a></li>\n"
"<li><a href=\"/abse4411/projz_renpy_translation/blob/devp_tmp/resources/codes/projz_injection.py\">resources/codes/projz_injection.py</a>: <a href=\"https://github.com/renpy/renpy/blob/master/renpy/translation/generation.py\">RenPy</a>, <a href=\"https://www.renpy.org/doc/html/license.html\" rel=\"nofollow\">MIT License for the code file</a></li>\n"
"<li>UI: PyQt5, it contains dual licenses: the GNU GPL v3 and the Riverbank Commercial License. See <a href=\"https://www.riverbankcomputing.com/software/pyqt/\" rel=\"nofollow\">here</a>.</li>\n"
"<li>UI theme: Qt-Material, <a href=\"https://github.com/UN-GCPDS/qt-material?tab=BSD-2-Clause-1-ov-file\">BSD-2-Clause license</a></li>\n"
"<li>Other python libs：<a href=\"https://github.com/abse4411/projz_renpy_translation/blob/devp/requirements_full.txt\">requirements_full.txt</a></li>\n"
"</ul></p></body></html>"))
        self.pushButton.setText(_translate("AboutDialogue", "Close"))
