# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sponsor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SponsorsDialog(object):
    def setupUi(self, SponsorsDialog):
        SponsorsDialog.setObjectName("SponsorsDialog")
        SponsorsDialog.resize(494, 390)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/proz_icon_simple.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SponsorsDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SponsorsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(SponsorsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("imgs/sponsor/thank.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(SponsorsDialog)
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.closesponsor_button = QtWidgets.QPushButton(SponsorsDialog)
        self.closesponsor_button.setObjectName("closesponsor_button")
        self.horizontalLayout_3.addWidget(self.closesponsor_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(SponsorsDialog)
        self.closesponsor_button.clicked.connect(SponsorsDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SponsorsDialog)

    def retranslateUi(self, SponsorsDialog):
        _translate = QtCore.QCoreApplication.translate
        SponsorsDialog.setWindowTitle(_translate("SponsorsDialog", "Sponsors"))
        self.label_2.setText(_translate("SponsorsDialog", "## 😘Thanks to my sponsors:\n"
"- 799190761\n"
"- ansan\n"
"\n"
"To become a sponsor, see [this](https://github.com/abse4411/projz_renpy_translation?tab=readme-ov-file#sponsor)."))
        self.closesponsor_button.setText(_translate("SponsorsDialog", "Close"))
