projz:
  project_path: './projz' # path for saving generating files, such as xls, html, json, etc.
  tmp_path: './projz/tmp' # path to save tmp file when launching a task
  translator:
    # It has a higher priority than index.write_cache_size when running translation cmd
    write_cache_size: 200 # The number of lines translated by the translator to cache before writing to disk
    max_workers: 10 # Max number of threads for ConcurrentTranslatorTemplate
    web:
      chrome_driver_path: 'D:\Users\Surface Book2\Downloads\chromedriver_win32\chromedriver.exe'
    ai:
      model_path: ''
      # available models: 'm2m100', 'mbart50', 'nllb200'
      model_name: 'mbart50'
      batch_size: 2
      # Language code can be found at: resources/translation/dl-translate_langcode.txt
      from_language: 'English'
      to_language: 'Chinese'
    translators:
      api_name: 'bing'
      # Language code can be found at: resources/translation/translators_langcode.txt
      from_language: 'auto'
      to_language: 'zh-Hans'
      # Translators is a library that aims to bring free, multiple, enjoyable translations to individuals and students in Python.
      preaccelerate:
        # kwargs for preaccelerate
        timeout: 2
      translate_text:
        # kwargs for translate_text, see https://github.com/UlionTse/translators/tree/master?tab=readme-ov-file#getting-started
        # Args of query_text, translator, from_language, and to_language, should not present here
        if_use_preacceleration: True
        sleep_seconds: 1
#        proxies:
#          http: 'http://127.0.0.1:10809'
#          https: 'http://127.0.0.1:10809'
  log:
    enable: False # enable logging
    console: True # log to console
    level: 'ERROR' # log level: 'CRITICAL','FATAL','ERROR','WARN', 'WARNING', 'INFO', 'DEBUG', 'NOTSET'
    path: './projz/logs' # path for logging
  index:
    # strip tags before translating texts
    strip_tag: False # This will reduce parsing errors when loading scripts
    write_cache_size: 2000 # large number of write operations will improves speed of read/write translations by reducing disk I/O.
    say_only: True # only import or export saystatements for dialogues
    # Rpy files to ignore when import or generate. ['options.rpy', 'common.rpy', 'projz_i18n_inject.rpy', 'screens.rpy']
    ignore: ['projz_i18n_inject.rpy']
    recycle_dir: 'resources/tl' # the dir for storing pre-translated string translations
  renpy:
    # enable debug console, https://www.renpy.org/doc/html/developer_tools.html#shift-o-console
    debug_console: True # one of True, False
    # enable developer mode, https://www.renpy.org/doc/html/developer_tools.html
    developer_mode: True # one of True, False, auto
    # these configs used for i18n injection
    i18n_menu:
      # you should not use a shortcut key which exists in the default RenPy keymap: https://www.renpy.org/doc/html/keymap.html
      # ctrl_K_i means Ctrl + i
      shortcut_key: 'ctrl_K_i' # use this shortcut_key to show our I18n menu
    # fonts listed in the i18n menu. we also add fonts configured in lang_map to the i18n menu
    # you can find download links in resources/fonts/readme.txt
    fonts:
      - 'resources/fonts/Roboto-Light.ttf'
      - 'resources/fonts/SourceHanSansLite.ttf'
      - 'resources/fonts/DejaVuSans.ttf'
    font_dir: 'projz_fonts/' # font dir in your_game/game, The dir should end with '/'.
    # the final languages listed in the i18n menu is determined by dirs in your_game/game/tl except "None"
    lang_map:
      - tl_name: 'indonesian'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Bahasa Indonesia'
      - tl_name: 'malay'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Bahasa Melayu'
      - tl_name: 'german'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Deutsch'
      - tl_name: 'spanish'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Español'
      - tl_name: 'french'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Français'
      - tl_name: 'italian'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Italiano'
      - tl_name: 'piglatin'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Igpay Atinlay'
      - tl_name: 'polish'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Polski'
      - tl_name: 'portuguese'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Português'
      - tl_name: 'finnish'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Suomi'
      - tl_name: 'vietnamese'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Tiếng Việt'
      - tl_name: 'turkish'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Türkçe'
      - tl_name: 'greek'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Ελληνικά'
      - tl_name: 'russian'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Русский'
      - tl_name: 'ukrainian'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Українська'
      - tl_name: 'arabic'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'العربية'
      - tl_name: 'japanese'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '日本語'
      - tl_name: 'schinese'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '简体中文'
      - tl_name: 'tchinese'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '繁體中文'
      - tl_name: 'korean'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '한국어'
