projz:
  project_path: './projz' # path for saving generating files, such as xls, html, json, etc.
  tmp_path: './projz/tmp' # path to save tmp file when launching a task
  translator:
    # It has a higher priority than index.write_cache_size when running translation cmd
    write_cache_size: 200 # The number of lines translated by the translator to cache before writing to disk
    max_workers: 10 # Max number of threads for ConcurrentTranslatorTemplate
    web:
      batch_separator: '@##@' # The separator add to between different texts in batch translator
      batch_max_textlen: 4096 # Max len of the final text sent to the real translator
      batch_size: 10 # how many texts are batched to send to the real translator at once
      chrome_driver_path: 'D:\Users\Surface Book2\Downloads\chromedriver-win64\chromedriver.exe'
    ai:
      model_path: ''
      # available models: 'm2m100', 'mbart50', 'nllb200'
      model_name: 'mbart50'
      batch_size: 2
      # Language code can be found at: resources/translation/dl-translate_langcode.txt
      from_language: 'English'
      to_language: 'Chinese'
    translators:
      batch_separator: '@##@' # The separator add to between different texts in batch translator
      batch_max_textlen: 4096 # Max len of the final text sent to the real translator
      batch_size: 10 # how many texts are batched to send to the real translator at once
      api_name: 'bing'
      # Language code can be found at: resources/translation/translators_langcode.txt
      from_language: 'auto'
      to_language: 'zh-Hans'
      # Translators is a library that aims to bring free, multiple, enjoyable translations to individuals and students in Python.
      preaccelerate:
        # kwargs for preaccelerate
        timeout: 2
      translate_text:
        # kwargs for translate_text, see https://github.com/UlionTse/translators/tree/master?tab=readme-ov-file#getting-started
        # Args of query_text, translator, from_language, and to_language, should not present here
        if_use_preacceleration: True
        sleep_seconds: 1
#        proxies:
#          http: 'http://127.0.0.1:10809'
#          https: 'http://127.0.0.1:10809'
    open_ai:
      batch_separator: '@##@' # The separator add to between different texts in batch translator
      batch_max_textlen: 1024 # Max len of the final text sent to the real translator
      batch_size: 5 # how many texts are batched to send to the real translator at once
      target_lang: 'Chinese'
      user_role: &user_role 'user'
      assistant_role: &assistant_role 'assistant'
      max_turns: 3 # Specify the maximum number of rounds for the conversation.
      langs: ['Afrikaans','Albanian','Amharic','Arabic','Armenian','Asturian','Azerbaijani','Bashkir','Belarusian','Bengali','Bosnian','Breton','Bulgarian','Burmese','Catalan','Cebuano','Central Khmer','Chinese','Croatian','Czech','Danish','Dutch','English','Estonian','Finnish','Flemish','French','Fulah','Gaelic','Galician','Ganda','Georgian','German','Greek','Gujarati','Haitian','Haitian Creole','Hausa','Hebrew','Hindi','Hungarian','Icelandic','Igbo','Iloko','Indonesian','Irish','Italian','Japanese','Javanese','Kannada','Kazakh','Khmer','Korean','Lao','Latvian','Letzeburgesch','Lingala','Lithuanian','Luxembourgish','Macedonian','Malagasy','Malay','Malayalam','Marathi','Moldavian','Moldovan','Mongolian','Nepali','Northern Sotho','Norwegian','Occitan','Oriya','Panjabi','Pashto','Persian','Polish','Portuguese','Punjabi','Pushto','Romanian','Russian','Scottish Gaelic','Serbian','Sindhi','Sinhala','Sinhalese','Slovak','Slovenian','Somali','Spanish','Sundanese','Swahili','Swati','Swedish','Tagalog','Tamil','Thai','Tswana','Turkish','Ukrainian','Urdu','Uzbek','Valencian','Vietnamese','Welsh','Western Frisian','Wolof','Xhosa','Yiddish','Yoruba','Zulu']
      models: ['qwen2:0.5b-instruct','qwen2:1.5b-instruct', 'qwen2:7b-instruct',
               'qwen:0.5b-chat','qwen:1.8b-chat', 'qwen:4b-chat', 'qwen:7b-chat', 'qwen:14b-chat', 'qwen:72b-chat',
               'gpt-4','gpt-4-0314','gpt-4-32k','gpt-4-32k-0314','gpt-3.5-turbo','gpt-3.5-turbo-0301']
      # Template Args
      # Args for initializing OpenAI() client
      init:
        base_url: http://localhost:11434/v1/
        api_key: 'ollama'
      chat:
        # Your client should have an endpoint whose url ends with "chat/completions". E.g., http://localhost:11434/v1/chat/completions
        # Args for client.chat.completions.create(), see https://platform.openai.com/docs/api-reference/chat/create
        completions:
#          temperature: 0.7
#          top_p: 0.8
          stream: false
          model: "qwen2:1.5b-instruct"
          messages:
            -
              role: "system"
              content: "You are a helpful assistant."
              # content: "You are a helpful assistant."
            -
              role: *user_role
#              content: "按下面的要求翻译文本:\n\
#                        1. 方括号或者花括号括起来的文本(例如[my_name], {size})不需要翻译.\n\
#                        2. 不需要对翻译结果做出解释.\n\
#                        现在把下面的文本翻译为{target_lang}:\n{text}"
              content: "Translate the text according to the following requirements:\n\
                        1. Text enclosed in square brackets or curly braces (e.g., [my_name], {{size}}) does not need to be translated.\n\
                        2. No explanation of the translation result is required.\n\
                        Now translate the following text into {target_lang}:\n{text}"
    realtime:
      host: '127.0.0.1'
      port: 8888
      retry_time: 10 # The retry time if server is crashed
      translator_wait_time: 0.5 # The max time to wait for the translation result in server
      string_request_time_out: 0.8 # The max time to wait for the server response of translating string in game
      dialogue_request_time_out: 1.0 # The max time to wait for the server response of translating dialogue in game
  log:
    enable: False # enable logging
    console: True # log to console
    level: 'ERROR' # log level: 'CRITICAL','FATAL','ERROR','WARN', 'WARNING', 'INFO', 'DEBUG', 'NOTSET'
    path: './projz/logs' # path for logging
  index:
    # scan more strings if found
    extra_scan: True
    # strip tags before translating texts
    strip_tag: False # This will reduce parsing errors when loading scripts
    ignore_meaningless_text: True # Filter texts that are not need to be translated when exporting (in sh, sj, se cmd), like: ..., !!!, etc.
    write_cache_size: 2000 # large number of write operations will improves speed of read/write translations by reducing disk I/O.
    say_only: True # only import or export saystatements for dialogues
    # Rpy files to ignore when import or generate. ['options.rpy', 'common.rpy', 'projz_i18n_inject.rpy', 'screens.rpy']
    ignore: ['projz_i18n_inject.rpy']
    recycle_dir: 'resources/tl' # the dir for storing pre-translated string translations
  renpy:
    # enable debug console, https://www.renpy.org/doc/html/developer_tools.html#shift-o-console
    debug_console: True # one of True, False
    # enable developer mode, https://www.renpy.org/doc/html/developer_tools.html
    developer_mode: True # one of True, False, auto
    # these configs used for i18n injection
    i18n_menu:
      # you should not use a shortcut key which exists in the default RenPy keymap: https://www.renpy.org/doc/html/keymap.html
      # ctrl_K_i means Ctrl + i
      shortcut_key: 'ctrl_K_i' # use this shortcut_key to show our I18n menu
    # fonts listed in the i18n menu. we also add fonts configured in lang_map to the i18n menu
    # you can find download links in resources/fonts/readme.txt
    font:
      save_dir: 'projz_fonts/' # font dir in your_game/game, The dir should end with '/'.
      default: 'SourceHanSansLite.ttf' # the default font to use (in realtime translator).
      list:
        - 'resources/fonts/Roboto-Light.ttf'
        - 'resources/fonts/SourceHanSansLite.ttf'
        - 'resources/fonts/DejaVuSans.ttf'
    # the final languages listed in the i18n menu is determined by dirs in your_game/game/tl except "None"
    lang_map:
      - tl_name: 'indonesian'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Bahasa Indonesia'
      - tl_name: 'malay'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Bahasa Melayu'
      - tl_name: 'german'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Deutsch'
      - tl_name: 'spanish'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Español'
      - tl_name: 'french'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Français'
      - tl_name: 'italian'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Italiano'
      - tl_name: 'piglatin'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Igpay Atinlay'
      - tl_name: 'polish'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Polski'
      - tl_name: 'portuguese'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Português'
      - tl_name: 'finnish'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'Suomi'
      - tl_name: 'vietnamese'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Tiếng Việt'
      - tl_name: 'turkish'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Türkçe'
      - tl_name: 'greek'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Ελληνικά'
      - tl_name: 'russian'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Русский'
      - tl_name: 'ukrainian'
        font: 'resources/fonts/Roboto-Light.ttf'
        title: 'Українська'
      - tl_name: 'arabic'
        font: 'resources/fonts/DejaVuSans.ttf'
        title: 'العربية'
      - tl_name: 'japanese'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '日本語'
      - tl_name: 'chinese'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '简体中文'
      - tl_name: 'schinese'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '简体中文'
      - tl_name: 'tchinese'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '繁體中文'
      - tl_name: 'korean'
        font: 'resources/fonts/SourceHanSansLite.ttf'
        title: '한국어'
