
name: Package

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .
        pypi_index_url: https://pypi.tuna.tsinghua.edu.cn/simple
        
    - name: Copy Files
      run: |
        cp config.yaml LICENSE README.md README_zh.md dist/windows
        cp -r imgs dist/windows

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: projz-Winndows_${{ inputs.tags }}
        path: dist/windows
