
name: Package

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        
    - name: Copy Files
      run: |
        cp config.yaml LICENSE README.md README_zh.md dist/windows
        cp -r imgs dist/windows
    
    - uses: actions/upload-artifact@v2
      with:
        name: projz-Winndows_${{ inputs.tags }} 
        path: dist/windows
